### ISSUE TITLE
Non-critical rules are erased from inline styles

### ISSUE THREAD

**Issue by Rarst** [GoogleChromeLabs/critters#112]
I have some `@font-face` rules for size-adjusted fallback fonts, to reduce CLS while web fonts are loading.

Out of the box critters doesn't seem to consider them critical CSS to inline (I've tried with `inlineFonts`, no difference for some reason?).

However stranger thing happens if I explicitly include them in HTML - critters actively _erases_ them from style block.

So given following style in head:

```css
<style>
  * {
    color: red !important;
  }

  @font-face {
    font-family: "Alegreya-fallback";
    size-adjust: 101%;
    src: local("Times New Roman");
  }

  @font-face {
    font-family: "Alegreya SC-fallback";
    size-adjust: 113.6%;
    src: local("Times New Roman");
  }

  @font-face {
    font-family: "Alegreya Sans-fallback";
    size-adjust: 86.56%;
    src: local("Arial");
  }
</style>
```

What's left from it after critters pass is:

```css
<style>* {
    color: red !important
}</style>
```

The font-face rules are gone - they are not there, or in critical CSS, or anywhere.

The log says:
```
Inlined 54 B (11% of original 464 B) of inline CSS.
```
Which is... strange. Dropping _any_ CSS from inline style seems actively destructive? It's not elsewhere, to be loaded later, it's just gone.

From some experiments same happens with any "non-critical" rule, that is such for a class not used on a page.
