### ISSUE TITLE
Local font source is not recognized as valid

### ISSUE THREAD

**Issue by Rarst** [GoogleChromeLabs/critters#113]
Only font faces having `src: url()` are treated as valid, so `src: local()` ones would always be considered invalid and dropped, even if they are detected as critical fonts.

```css
@font-face {
  font-family: "Alegreya-fallback";
  size-adjust: 101%;
  src: local("Times New Roman");
}
```

https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters/src/index.js#L568-L587

Related #112
