### ISSUE TITLE
0% -> Unmatched selector: %

### ISSUE THREAD

**Issue by jllodra** [GoogleChromeLabs/critters#86]
This is happening in an angular12 project, which is using critters under the hood I assume.

```
1 rules skipped due to selector errors:
  0% -> Unmatched selector: %
```

In my styles.scss file I have:

```scss
  @keyframes bounce {
    from {
      opacity: 0.10;
      transform: scale(0.9);
    }

    to {
      opacity: 1;
      transform: scale(1);
    }
  }
```

If I remove this code, the warning disappears.

Probably the scss compiler is turning the `from` into a `0%`, this is just a guess.
